<?php
// Generated by ZF2's ./bin/classmap_generator.php
// 
// Run in this directory:
// $ php ../../bin/classmap_generator.php
return array(
  // 'TWeb\Module'                        => __DIR__ . '/Module.php',
  // 'TWeb\Model\PageContent'             => __DIR__ . '/src/TWeb/Model/PageContent.php',
  // 'TWeb\Model\Email'                   => __DIR__ . '/src/TWeb/Model/Email.php',
  // 'TWeb\Controller\AbstractController' => __DIR__ . '/src/TWeb/Controller/AbstractController.php',
  // 'TWebTest\Model\PageContentTest'     => __DIR__ . '/tests/TWebTest/Model/PageContentTest.php',
  // 'TWebTest\Bootstrap'                 => __DIR__ . '/tests/Bootstrap.php',
);
