<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TWeb\Module'                        => __DIR__ . '/Module.php',
    'TWeb\Controller\NumberController' => __DIR__ . '/src/TWeb/Controller/AbstractController.php',
);